/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicHooksSyncChinaSheetRouteImport } from './routes/api/public/hooks/sync-china-sheet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncChinaSheetRoute =
  ApiPublicHooksSyncChinaSheetRouteImport.update({
    id: '/api/public/hooks/sync-china-sheet',
    path: '/api/public/hooks/sync-china-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/sync-china-sheet': typeof ApiPublicHooksSyncChinaSheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/sync-china-sheet': typeof ApiPublicHooksSyncChinaSheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/hooks/sync-china-sheet': typeof ApiPublicHooksSyncChinaSheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin/' | '/api/public/leads' | '/api/public/hooks/sync-china-sheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/admin' | '/api/public/leads' | '/api/public/hooks/sync-china-sheet'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/api/public/leads'
    | '/api/public/hooks/sync-china-sheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicHooksSyncChinaSheetRoute: typeof ApiPublicHooksSyncChinaSheetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-china-sheet': {
      id: '/api/public/hooks/sync-china-sheet'
      path: '/api/public/hooks/sync-china-sheet'
      fullPath: '/api/public/hooks/sync-china-sheet'
      preLoaderRoute: typeof ApiPublicHooksSyncChinaSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicHooksSyncChinaSheetRoute: ApiPublicHooksSyncChinaSheetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
